# Generated by Django 5.0.3 on 2024-05-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Busno', models.IntegerField()),
                ('Departure_Time', models.CharField(max_length=8)),
                ('Destinations', models.CharField(max_length=500)),
                ('Seats_Available', models.IntegerField()),
                ('TicketCosts', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busno', models.IntegerField()),
                ('destination', models.CharField(max_length=50)),
                ('no_of_persons', models.IntegerField()),
            ],
        ),
    ]
